/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;

public class CombatResultView extends javax.swing.JFrame {

    CombatResult result;

    public CombatResultView() {
        
        initComponents();
    }
    
    public void setCombatResult(CombatResult cr) {
        
        result = cr;
        
        switch(result){
            
            case Lose:
                
                cResult.setText("Pierdes el combate");
                Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LOSE.gif")));
                break;
                
            case LoseAndEscape: 
                
                cResult.setText("Has logrado escapar");
                //Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LOSEANDESCAPE.gif")));
                break;
                
            case LoseAndDie: 
                
                cResult.setText("Pierdes y mueres");
                Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LOSEANDDIE.gif")));
                break;
                
            case Win: 
                
                cResult.setText("Ganas el combate");
                //Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/WIN.gif")));
                break;
                    
            case WinAndWinGame: 
                
                cResult.setText("Has ganado la partida");
                Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/WINANDWINGAME.gif")));
                break;
            
        }
        
        repaint();
    }
    
    public void showView() {
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cResult = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Napakalaki");
        setMaximumSize(new java.awt.Dimension(510, 300));
        setMinimumSize(new java.awt.Dimension(510, 300));
        getContentPane().setLayout(null);

        cResult.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        cResult.setForeground(new java.awt.Color(204, 204, 204));
        cResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cResult);
        cResult.setBounds(30, 20, 442, 103);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(200, 210, 107, 23);

        Background.setMaximumSize(new java.awt.Dimension(510, 300));
        Background.setMinimumSize(new java.awt.Dimension(510, 300));
        Background.setPreferredSize(new java.awt.Dimension(510, 300));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 510, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        
        this.setVisible(false);
        
        if (result == CombatResult.WinAndWinGame)
            
            System.exit(0);
    }//GEN-LAST:event_OKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton OK;
    private javax.swing.JLabel cResult;
    // End of variables declaration//GEN-END:variables
}
