/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;

/**
 *
 */

public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    CombatResult result;
    CombatResultView crView = new CombatResultView();
    
    public void setNapakalaki(Napakalaki napakalaki){
    
        napakalakiModel = napakalaki;
        
        player.setNapakalaki(napakalakiModel);
        
        if (napakalakiModel.getCurrentPlayer() != null)
        
            player.setPlayer(napakalakiModel.getCurrentPlayer());
        
        if (napakalakiModel.getCurrentMonster() != null)
        
            monster.setMonster(napakalakiModel.getCurrentMonster());
        
        monster.setVisible(false);
        meet.setEnabled(true);
        combat.setEnabled(false);
        next.setEnabled(false);
        
        repaint();
    }
    
    
    public NapakalakiView() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Game = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        meet = new javax.swing.JButton();
        player = new GUI.PlayerView();
        combat = new javax.swing.JButton();
        monster = new GUI.MonsterView();
        error = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Napakalaki");
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        Game.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Game.setMaximumSize(new java.awt.Dimension(900, 520));
        Game.setMinimumSize(new java.awt.Dimension(900, 520));
        Game.setOpaque(false);
        Game.setPreferredSize(new java.awt.Dimension(900, 520));

        next.setText("Siguiente turno");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        meet.setText("Conoce al monstruo");
        meet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetActionPerformed(evt);
            }
        });

        player.setMaximumSize(new java.awt.Dimension(392, 394));
        player.setOpaque(false);

        combat.setText("¡Lucha!");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        monster.setMaximumSize(new java.awt.Dimension(405, 394));
        monster.setMinimumSize(new java.awt.Dimension(405, 394));
        monster.setOpaque(false);
        monster.setPreferredSize(new java.awt.Dimension(405, 394));

        error.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setMaximumSize(new java.awt.Dimension(140, 21));
        error.setMinimumSize(new java.awt.Dimension(140, 21));
        error.setPreferredSize(new java.awt.Dimension(140, 21));

        javax.swing.GroupLayout GameLayout = new javax.swing.GroupLayout(Game);
        Game.setLayout(GameLayout);
        GameLayout.setHorizontalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GameLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(meet)
                .addGap(28, 28, 28)
                .addComponent(combat)
                .addGap(35, 35, 35)
                .addComponent(next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        GameLayout.setVerticalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(meet)
                        .addComponent(combat)
                        .addComponent(next))
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        getContentPane().add(Game);
        Game.setBounds(0, 0, 900, 550);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Libro.gif"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 900, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed

        result = napakalakiModel.developCombat();

        crView.setCombatResult(result);
        crView.showView();

        setNapakalaki(napakalakiModel);

        player.setEnable(true);
        next.setEnabled(true);
        combat.setEnabled(false);
        meet.setEnabled(false);
        monster.setVisible(true);

        repaint();
    }//GEN-LAST:event_combatActionPerformed

    private void meetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetActionPerformed

        monster.setVisible(true);

        player.setEnable(false);
        combat.setEnabled(true);

        repaint();

    }//GEN-LAST:event_meetActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        boolean allowed = false;

        allowed = napakalakiModel.nextTurn();

        if (!allowed) {

            error.setText("You shall not pass...");
            repaint();
        }

        else {

            monster.setVisible(false);
            error.setText("");
            setNapakalaki(napakalakiModel);
        }

    }//GEN-LAST:event_nextActionPerformed

    public void showView() {
        
        this.setVisible(true);
        
    }
    
    public CombatResult getCombatResult () {
        
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Game;
    private javax.swing.JButton combat;
    private javax.swing.JLabel error;
    private javax.swing.JButton meet;
    private GUI.MonsterView monster;
    private javax.swing.JButton next;
    private GUI.PlayerView player;
    // End of variables declaration//GEN-END:variables
}
