/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;

/**
 *
 */
public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel;

    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        treasurekind = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goldcoins = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        minbonus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maxbonus = new javax.swing.JLabel();

        jLabel1.setText("Name:");

        name.setText("jLabel2");

        jLabel3.setText("Treasure Kind:");

        treasurekind.setText("jLabel4");

        jLabel5.setText("Gold Coins:");

        goldcoins.setText("jLabel6");

        jLabel7.setText("Min.Bonus:");

        minbonus.setText("jLabel8");

        jLabel9.setText("Max.Bonus:");

        maxbonus.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxbonus)
                            .addComponent(goldcoins)
                            .addComponent(minbonus)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(treasurekind, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(name)))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treasurekind)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goldcoins)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minbonus)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxbonus)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goldcoins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel maxbonus;
    private javax.swing.JLabel minbonus;
    private javax.swing.JLabel name;
    private javax.swing.JLabel treasurekind;
    // End of variables declaration//GEN-END:variables

    public void setTreasure (Treasure t){
    
        treasureModel = t;
        name.setText(treasureModel.getName());
        treasurekind.setText(treasureModel.TypetoString());
        goldcoins.setText(Integer.toString(treasureModel.getGoldCoins()));
        minbonus.setText(Integer.toString(treasureModel.getMinBonus()));
        maxbonus.setText(Integer.toString(treasureModel.getMaxBonus()));
        
        repaint();
    }
    
}
